// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class AuthHeaderCell : UITableViewCell
	{
		public AuthHeaderCell (IntPtr handle) : base (handle)
		{
		}

		public AuthHeaderCell(NSString cellId) : base(UITableViewCellStyle.Default, cellId)
        {

		}
	}
}
