// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class AuthViewCell : UITableViewCell
	{
		public AuthViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
