// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class FrackedTableCell : UITableViewCell
	{
		private static NSString Key = new NSString("FrackedTableCell");

		public FrackedTableCell() : base(UITableViewCellStyle.Default, Key)
		{
		}

		public FrackedTableCell (IntPtr handle) : base (handle)
		{
		}

		public FrackedTableCell(NSString cellId) : base(UITableViewCellStyle.Default, cellId)
		{
			
		}

		public void SetProgress(string title, int progress)
		{
			lblTitle.Text = title;
			lblProgress.Text = progress.ToString();
		}
	}
}
