// This file has been autogenerated from a class added in the UI designer.

using System;
using CloudCoin_SafeScan;
using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class FrackedTableCell : UITableViewCell
	{
		private static NSString Key = new NSString("FrackedTableCell");

		public FrackedTableCell() : base(UITableViewCellStyle.Default, Key)
		{
		}

		public FrackedTableCell (IntPtr handle) : base (handle)
		{
		}

		public FrackedTableCell(NSString cellId) : base(UITableViewCellStyle.Default, cellId)
		{
			
		}

		public void SetProgress(CloudCoin coin)
		{
			lblTitle.Text = coin.sn + "  " + GetDenominations(coin.denomination) 
				+ "\t" + coin.StatusText;
			//lblProgress.Text = progress.ToString();
		}

		private string GetDenominations(CloudCoin.Denomination denomination)
		{
			switch (denomination)
			{
				case CloudCoin.Denomination.One:
					return "1";
				case CloudCoin.Denomination.Five:
					return "5";
				case CloudCoin.Denomination.Quarter:
					return "25";
				case CloudCoin.Denomination.Hundred:
					return "100";
				case CloudCoin.Denomination.KiloQuarter:
					return "250";
			}

			return "";
		}
	}
}
