// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using CloudCoin_SafeScan;
using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class BankViewController : BaseFormSheet
	{
		private List<CloudCoin> frackedList;
        private AppDelegate appDelegate;

        public EventHandler FixFrackedTouched;
		
		public BankViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			InitializeProperties();

			InitializeMethods();
		}

		private void InitializeProperties()
		{
            appDelegate = (AppDelegate)UIApplication.SharedApplication.Delegate;

			frackedList = new List<CloudCoin>(Safe.Instance.FrackedCoinsList);

			if (frackedList.Count == 0)
			{
				SetEnableButton(btnFixFracked, false);
			}
			else
			{
                SetEnableButton(btnFixFracked, true);
			}
		}

		private void SetEnableButton(UIButton button, bool isEnabled)
		{
            button.Hidden = !isEnabled;
		}

		private void InitializeMethods()
		{
			btnClose.TouchUpInside += (sender, e) =>
			{
				RemoveAnimate();
			};

			btnFixFracked.TouchUpInside += async (sender, e) =>
			{
                if (!appDelegate.IsFrackedBackground())
				    FixFrackedTouched.Invoke(this, null);
				await ApplicationLogic.FixSelected();
			};

			Safe.Instance.SafeChanged += SafeContentChanged;
			Safe.Instance.onSafeContentChanged(new EventArgs());
		}

		private void SafeContentChanged(object sender, EventArgs e)
		{
			var safe = Safe.Instance;

			if (safe != null)
			{
                lblSumInBank.Text = safe.Contents.SumInStack.ToString();
				lblAuthOne.Text = safe.Ones.GoodQuantity.ToString();
				lblAuthFive.Text = safe.Fives.GoodQuantity.ToString();
				lblAuth25.Text = safe.Quarters.GoodQuantity.ToString();
				lblAuth100.Text = safe.Hundreds.GoodQuantity.ToString();
				lblAuth250.Text = safe.KiloQuarters.GoodQuantity.ToString();

				lblFrackedOne.Text = safe.Ones.FractionedQuantity.ToString();
				lblFrackedFive.Text = safe.Fives.FractionedQuantity.ToString();
				lblFracked25.Text = safe.Quarters.FractionedQuantity.ToString();
				lblFracked100.Text = safe.Hundreds.FractionedQuantity.ToString();
				lblFracked250.Text = safe.KiloQuarters.FractionedQuantity.ToString();
			}
		}
	}
}
