// This file has been autogenerated from a class added in the UI designer.

using System;
using CloudCoin_SafeScan;
using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class BankViewController : BaseFormSheet
	{
		public EventHandler FixFrackedTouched;

		public BankViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			InitializeProperties();

			InitializeMethods();
		}

		private void InitializeProperties()
		{
			
		}

		private void InitializeMethods()
		{
			btnClose.TouchUpInside += (sender, e) =>
			{
				RemoveAnimate();
			};

			btnFixFracked.TouchUpInside += (sender, e) =>
			{
				FixFrackedTouched.Invoke(this, null);
				//await ApplicationLogic.FixSelected();
			};

			Safe.Instance.SafeChanged += SafeContentChanged;
			Safe.Instance.onSafeContentChanged(new EventArgs());
		}

		private void SafeContentChanged(object sender, EventArgs e)
		{
			var safe = Safe.Instance;

			if (safe != null)
			{
				lblAuthOne.Text = safe.Ones.GoodQuantity.ToString();
				lblAuthFive.Text = safe.Fives.GoodQuantity.ToString();
				lblAuth25.Text = safe.Quarters.GoodQuantity.ToString();
				lblAuth100.Text = safe.Hundreds.GoodQuantity.ToString();
				lblAuth250.Text = safe.KiloQuarters.GoodQuantity.ToString();

				lblFrackedOne.Text = safe.Ones.FractionedQuantity.ToString();
				lblFrackedFive.Text = safe.Fives.FractionedQuantity.ToString();
				lblFracked25.Text = safe.Quarters.FractionedQuantity.ToString();
				lblFracked100.Text = safe.Hundreds.FractionedQuantity.ToString();
				lblFracked250.Text = safe.KiloQuarters.FractionedQuantity.ToString();
			}
		}
	}
}
