// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class BankViewController : BaseFormSheet
	{
		public BankViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			InitializeMethods();
		}

		private void InitializeMethods()
		{
			btnClose.TouchUpInside += (sender, e) =>
			{
				RemoveAnimate();
			};
		}
	}
}
