// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class FixFrackedViewController : BaseFormSheet
	{
		public FixFrackedViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			InitializeProperties();

			IntializeMethods();
		}

		private void InitializeProperties()
		{
			frackedTableView.Source = new FrackedTableSource(new string[] { "1", "2", "3", "4" });
		}

		private void IntializeMethods()
		{
			btnClose.TouchUpInside += (sender, e) =>
			{
				RemoveAnimate();
			};
		}
	}

	public class FrackedTableSource : UITableViewSource
	{

		string[] TableItems;
		NSString CellIdentifier = new NSString("FrackedTableCell");

		public FrackedTableSource(string[] items)
		{
			TableItems = items;
		}

		public override nint RowsInSection(UITableView tableview, nint section)
		{
			return TableItems.Length;
		}

		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			var cell = (FrackedTableCell)tableView.DequeueReusableCell(CellIdentifier);
			string item = TableItems[indexPath.Row];

			//---- if there are no cells to reuse, create a new one
			if (cell == null)
			{
				cell = new FrackedTableCell(CellIdentifier);
			}
			cell.SetProgress("33", 3);

			return cell;
		}
	}
}
