// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using CloudCoin_SafeScan;
using Foundation;
using GalaSoft.MvvmLight.Threading;
using UIKit;

namespace CloudCoinIOS
{
	public partial class ImportViewController : BaseFormSheet
	{
		private List<string> urlList;

		public ImportViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			InitializeProperties();

			InitializeMethods();
		}

		private void InitializeProperties()
		{
			var appDelegate = (AppDelegate)UIApplication.SharedApplication.Delegate;
			urlList = appDelegate.UrlList;
		}

		private void InitializeMethods()
		{
			btnImport.TouchUpInside += (sender, e) =>
			{
				var coinFile = ApplicationLogic.ScanSelected(urlList);
				if (coinFile != null)
				{
					btnCancel.Hidden = true;
					btnImport.Hidden = true;

				}
				else
				{
					RemoveAnimate();
				}
			};

			btnCancel.TouchUpInside += (sender, e) => 
			{ 
                RemoveAnimate();
			};

			RAIDA.Instance.StackScanCompleted += StackScanCompleted;
		}
		private void StackScanCompleted(object o, StackScanCompletedEventArgs e)
		{
			RemoveAnimate();
		}
	}
}
