// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;
using System.Text;
using CloudCoin_SafeScan;
using CryptSharp;
using Foundation;
using PassKit;
using UIKit;

namespace CloudCoinIOS
{
	public partial class MainViewController : UIViewController
	{
		private CloudCoinFile coinFile;

		public MainViewController (IntPtr handle) : base (handle)
		{
			
		}

		public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear(animated);

			//var paths = new NSSearchPath()
		}

		public override void ViewDidLayoutSubviews()
		{
			makeRoundRectView(importView);
			makeRoundRectView(bankView);
			makeRoundRectView(exportView);

			base.ViewDidLayoutSubviews();
		}

		private void makeRoundRectView(UIView view)
		{
			view.Layer.CornerRadius = view.Bounds.Height / 2f;
			view.Layer.MasksToBounds = true;
		}

		partial void OnImportTouched(Foundation.NSObject sender)
		{
			var modalImportViewController = (ImportViewController)GetViewController("ImportViewController");
			modalImportViewController.ShowInView(View, true);
			modalImportViewController.CompletedWithPassword += CompletedWithPassword;
		}

		private void CompletedWithPassword(CloudCoinFile ccFile)
		{
			var fileInfo = new FileInfo(Safe.GetSafeFilePath());
			NewPassViewController newPassViewController;
			EnterPassViewController enterPassViewController;

			this.coinFile = ccFile;

			if (!fileInfo.Exists)
			{
				newPassViewController = (NewPassViewController)GetViewController("NewPassViewController");
				newPassViewController.ShowInView(View, true);
				newPassViewController.FinishSetPassword += FinishDoPassword;
					
			}
			else
			{
				enterPassViewController = (EnterPassViewController)GetViewController("EnterPassViewController");
				enterPassViewController.ShowInView(View, true);
				enterPassViewController.FinishEnterPassword += FinishDoPassword;
			}

			//Safe.Instance?.Add(coinFile.Coins);
		}

		private void FinishDoPassword(string password)
		{
			UserInteract.Password = password;
			Safe.Instance?.Add(coinFile.Coins);

			var	modalBankViewController = (BankViewController)GetViewController("BankViewController");
			modalBankViewController.ShowInView(View, true);
		}

		partial void OnExportTouched(Foundation.NSObject sender)
		{
			var modalExportViewController = (ExportViewController)GetViewController("ExportViewController");
			modalExportViewController.ShowInView(View, true);
		}

		partial void OnBankTouched(Foundation.NSObject sender)
		{
			var modalBankViewController = (BankViewController)GetViewController("BankViewController");
			modalBankViewController.ShowInView(View, true);
		}

		private BaseFormSheet GetViewController(string regId)
		{
			return (BaseFormSheet)Storyboard.InstantiateViewController(regId);
		}

		public override UIStatusBarStyle PreferredStatusBarStyle()
		{
			return UIStatusBarStyle.LightContent;
		}
	}
}
