// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class NewPassViewController : BaseFormSheet
	{
		public delegate void FinishSetPasswordDelegate(string password);
		public event FinishSetPasswordDelegate FinishSetPassword;

		public NewPassViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			InitializeProperties();

            InitializeMethods();
		}

		private void InitializeProperties()
		{
			txtPassword.BecomeFirstResponder();
		}

		private void InitializeMethods()
		{
			btnOk.TouchUpInside += (sender, e) =>
			{
				if (txtPassword.Text.Length < 5)
				{
					ShowAlert("Password", "Password is too short. Use more than 5 characters.", new string[] { "Ok" });
				}
				else if (txtPassword.Text != txtCfrPassword.Text)
				{
					ShowAlert("Password", "Passwords don't match.", new string[] { "Ok" });
				}
				else
				{
					FinishSetPassword(txtPassword.Text);
					RemoveAnimate();
				}
			};
		}
	}
}
