// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class NewPassViewController : BaseFormSheet
	{
		public delegate void FinishSetPasswordDelegate(string password);
		public event FinishSetPasswordDelegate FinishSetPassword;

		public NewPassViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			InitializeProperties();

            InitializeMethods();
		}

		private void InitializeProperties()
		{
			txtPassword.BecomeFirstResponder();

            //textConstraintHeight.Constant = GetHeightFromText(txtExplain.Text);
		}

        private nfloat GetHeightFromText(string text)
        {
            var explanation = new NSString(text);

            var textSize = new CGSize(txtExplain.Frame.Width, 1000);
            var size = explanation.GetBoundingRect(textSize, 
                                        NSStringDrawingOptions.UsesLineFragmentOrigin, 
                                        new UIStringAttributes()
							            {
							                Font = UIFont.FromName("HelveticaNeue", 14f)
							            }, 
                                        null);
            return size.Height;
		}

		private void InitializeMethods()
		{
			btnOk.TouchUpInside += (sender, e) =>
			{
				if (txtPassword.Text.Length < 5)
				{
					ShowAlert("Password", "Password is too short. Use more than 5 characters.", new string[] { "Ok" });
				}
				else if (txtPassword.Text != txtCfrPassword.Text)
				{
					ShowAlert("Password", "Passwords don't match.", new string[] { "Ok" });
				}
				else
				{
					FinishSetPassword(txtPassword.Text);
					RemoveAnimate();
				}
			};

            btnCancel.TouchUpInside += (sender, e) => {
                RemoveAnimate();
            };
		}
	}
}
