// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class PasswordViewController : UIViewController
	{
		public PasswordViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear(animated);
		}



	}
}
