// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudCoinIOS
{
    public partial class SettingsViewController : BaseFormSheet
	{
        private UIColor tintColor = UIColor.FromRGB(52, 142, 251);

		public SettingsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitProperties();
            InitMethods();
        }

        private void InitProperties()
        {
            var appDelegate = (AppDelegate)UIApplication.SharedApplication.Delegate;

            switchFracked.On = appDelegate.IsFrackedBackground();
            switchZip.On = appDelegate.IsSupportZip();

            switchFracked.OnTintColor = tintColor;
            switchZip.OnTintColor = tintColor;

            switchFracked.ValueChanged += (sender, e) => {
                appDelegate.SetFrackedBackground(switchFracked.On);
            };

            switchZip.ValueChanged += (sender, e) => {
                appDelegate.SetZip(switchZip.On);
            };
        }

        private void InitMethods()
        {
			btnClose.TouchUpInside += (sender, e) =>
			{
				RemoveAnimate();
			};
        }
	}
}
