// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudCoinIOS
{
    public partial class SettingsViewController : BaseFormSheet
	{
		public SettingsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitProperties();
            InitMethods();
        }

        private void InitProperties()
        {
            var defaults = NSUserDefaults.StandardUserDefaults;

            switchFracked.On = defaults.BoolForKey("Fracked");
            switchZip.On = defaults.BoolForKey("Zip");

            switchFracked.OnTintColor = UIColor.FromRGB(52,142,251);
            switchZip.OnTintColor = UIColor.FromRGB(52, 142, 251);

            switchFracked.ValueChanged += (sender, e) => {
                defaults.SetBool(switchFracked.On, "Fracked");    
            };

            switchZip.ValueChanged += (sender, e) => {
                defaults.SetBool(switchZip.On, "Zip");
            };
        }

        private void InitMethods()
        {
			btnClose.TouchUpInside += (sender, e) =>
			{
				RemoveAnimate();
			};
        }
	}
}
