// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using UIKit;

namespace CloudCoinIOS
{
	public partial class ZipPasswordViewController : BaseFormSheet
	{
        private TaskCompletionSource<string> tcs;

        public bool IsInput { get; set; }
        public EventHandler<bool> EnterPasswordHandler;

		public ZipPasswordViewController (IntPtr handle) : base (handle)
		{
            
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitProperties();

            InitMethods();
        }

        private void InitProperties() {
            txtPassword.BecomeFirstResponder();
        }

        private void InitMethods() {

            tcs = new TaskCompletionSource<string>();

            btnOk.TouchUpInside += (sender, e) => {

                if (txtPassword.Text != txtCfrPassword.Text){
                    ShowAlert("Password", "Passwords don't match.", new string[] { "Ok" });
                    return;
                }
                if (IsInput)
                {
                    Console.WriteLine("IsInputed");
                }
                else
                {
                    
                }
                tcs.TrySetResult((string)txtPassword.Text);
            };

            btnCancel.TouchUpInside += (sender, e) => {
                tcs.TrySetResult("");
            };
        }

        public Task<string> GetEnterPassword()
        {
            return tcs.Task;
        }
	}
}
